# Pandas

In [3]:
import pandas as pd 
import numpy as np

In [9]:

# Create a DataFrame manually
data = {'Name': ['Mary', 'Bob', 'Charlie', 'David', 'Eve'],
        'Age': [25, 30, 22, 35, 28],
        'City': ['Nairobi', 'Lagos', 'Juba', 'Accra', 'New York'],
        'Score': [85, 92, 78, 95, 88]}

#Converting a Data to a Dataframe
my_data =pd.DataFrame(data)
print(my_data)

      Name  Age      City  Score
0     Mary   25   Nairobi     85
1      Bob   30     Lagos     92
2  Charlie   22      Juba     78
3    David   35     Accra     95
4      Eve   28  New York     88

In [19]:
my_data.head() #view first 5 elements of the dataframe
# print(my_data.head())
# display(my_data.head())

      Name  Age      City  Score
0     Mary   25   Nairobi     85
1      Bob   30     Lagos     92
2  Charlie   22      Juba     78
3    David   35     Accra     95
4      Eve   28  New York     88

In [23]:
my_data.tail(3) # prints the last 5 elements by default

      Name  Age      City  Score
2  Charlie   22      Juba     78
3    David   35     Accra     95
4      Eve   28  New York     88

In [25]:
# It gives general info abt the dataframe 
# 1. The columns and rows 
# 2. The data types
# 3.The number/quantity  of data -missing data
# 

my_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    5 non-null      object
 1   Age     5 non-null      int64
 2   City    5 non-null      object
 3   Score   5 non-null      int64
dtypes: int64(2), object(2)
memory usage: 292.0+ bytes

In [31]:
# Describe - The statistical bit about a dataset
# my_data.describe()
print(my_data.describe())

             Age      Score
count   5.000000   5.000000
mean   28.000000  87.600000
std     4.949747   6.580274
min    22.000000  78.000000
25%    25.000000  85.000000
50%    28.000000  88.000000
75%    30.000000  92.000000
max    35.000000  95.000000

In [33]:
# counting the missing data in a dataset and find the sum 
my_data.isnull().sum()

Name     0
Age      0
City     0
Score    0
dtype: int64

In [39]:
# unique values 
print(my_data['City'].unique())

#Count the unique values 
print(my_data['City'].value_counts())

['Nairobi' 'Lagos' 'Juba' 'Accra' 'New York']
City
Nairobi     1
Lagos       1
Juba        1
Accra       1
New York    1
Name: count, dtype: int64